name: test

permissions:
  contents: write

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          powershell ./install.ps1
          Get-ChildItem ./mpv

          powershell ./install.ps1 mpv-easy
          Get-ChildItem ./mpv-easy

          powershell ./install.ps1 mpv-uosc
          Get-ChildItem ./mpv-uosc

          powershell ./install.ps1 mpv-modernx
          Get-ChildItem ./mpv-modernx
